add_settings_for_operation
sushka2023/sushka-shop-fe pull request #43
Opened 2024-01-30 22:00 UTC by Tkachenko01001

2024-01-30 23:58 UTC, pqoqubbw requested changes

2024-01-30 23:58 UTC, pqoqubbw commented on src/App.tsx
> +  const accessToken = Cookies.get('token')
`token` should be a variable like `const COOKIE_TOKEN_NAME = "token"`

2024-01-30 23:58 UTC, pqoqubbw commented on src/App.tsx
> +        currentUser({ accessToken: accessToken, operationType: 'currentUser' })
```suggestion
        currentUser({ accessToken, operationType: 'currentUser' })
```

2024-01-30 23:58 UTC, pqoqubbw commented on src/axios/settings.ts
> +  baseURL: 'https://www.test-store.shop/'
should be as a `const`

2024-01-30 23:58 UTC, pqoqubbw commented on src/axios/settings.ts
> +    const accessToken = Cookies.get('token')
use variable

2024-01-30 23:58 UTC, pqoqubbw commented on src/axios/settings.ts
> +    }
```suggestion
    if (accessToken && config.headers) {
      config.headers.Authorization = `Bearer ${accessToken}`
    }
```

2024-01-30 23:58 UTC, pqoqubbw commented on src/components/Layout/header/header-nav/DropdownList.tsx
> +        allCategories.map((category) => {
```suggestion
      {allCategories?.map((category) => {
```

2024-01-30 23:58 UTC, pqoqubbw commented on src/components/Layout/header/header-nav/HeaderNavList.tsx
> +  const homePath = location.pathname === '/'
Use the right name convention for boolean, ex `isHomePath`

2024-01-30 23:58 UTC, pqoqubbw commented on src/components/Layout/header/header-nav/HeaderNavList.tsx
> +        <Link to={'/review'} className={styles.listNavLink}>
```suggestion
        <Link to="/review" className={styles.listNavLink}>
```

2024-01-30 23:58 UTC, pqoqubbw commented on src/components/Layout/header/header-nav/headerNav.tsx
> +  const homePath = location.pathname === '/'
same

2024-01-30 23:58 UTC, pqoqubbw commented on src/components/Layout/header/header-nav/headerNav.tsx
> +    if (!allCategories) {
maybe you meant `!allCategories?.length`?

2024-01-30 23:58 UTC, pqoqubbw commented on src/components/privste-route/index.tsx
> +  const accessToken = Cookies.get('token')
use token variable

2024-01-30 23:58 UTC, pqoqubbw commented on src/redux/authentication/operation.ts
> +      Cookies.set('token', response.data.access_token, { expires: 7 })
same

2024-01-30 23:58 UTC, pqoqubbw commented on src/redux/authentication/operation.ts
> +      Cookies.remove('token')
same

2024-01-31 01:13 UTC, Tkachenko01001 commented on src/App.tsx
> +  const accessToken = Cookies.get('token')
done

2024-01-31 01:14 UTC, Tkachenko01001 commented on src/App.tsx
> +        currentUser({ accessToken: accessToken, operationType: 'currentUser' })
done

2024-01-31 11:49 UTC, pqoqubbw requested changes
maybe it will be better to create custom hook like `useCookie` which allow you to get and set your value

2024-01-31 11:49 UTC, pqoqubbw commented on src/axios/settings.ts
> +const COOKIE_TOKEN_NAME = 'token'
just export already created variable

2024-01-31 11:49 UTC, pqoqubbw commented on src/components/privste-route/index.tsx
> +const COOKIE_TOKEN_NAME = 'token'
same

2024-01-31 11:49 UTC, pqoqubbw commented on src/redux/authentication/operation.ts
> +const COOKIE_TOKEN_NAME = 'token'
same

2024-02-01 15:07 UTC, pqoqubbw requested changes

2024-02-01 15:07 UTC, pqoqubbw commented on src/App.tsx
> +  const { getToken } = useCookieMenager()
typo, manager

2024-02-01 15:07 UTC, pqoqubbw commented on src/components/Layout/header/header-nav/CrmLink.tsx
> +      {user && (user.role === 'admin' || user.role === 'moderator') && (
```suggestion
      {(user?.role === 'admin' || user?.role === 'moderator') && (
```

2024-02-01 15:24 UTC, pqoqubbw approved these changes

2024-02-01 15:24 UTC, merged