Feature/orders
sushka2023/sushka-shop-fe pull request #75
Opened 2024-07-10 15:31 UTC by Tkachenko01001

2024-07-14 01:38 UTC, pqoqubbw requested changes

2024-07-14 01:38 UTC, pqoqubbw commented on src/pages/order-page/index.tsx
> +          <Box>{}</Box>
?

2024-07-14 01:38 UTC, pqoqubbw commented on package.json
> +    "md5": "^2.3.0",
for what do you need this package?

2024-07-14 01:38 UTC, pqoqubbw commented on package.json
> +    "crypto-js": "^4.2.0",
same here

2024-07-14 01:38 UTC, pqoqubbw commented on .env
do not push this file to github, this should be local only

2024-07-29 18:51 UTC, pqoqubbw requested changes

2024-07-29 18:51 UTC, pqoqubbw commented on .env
do not push this `.env` to public

2024-07-29 18:51 UTC, pqoqubbw commented on package-lock.json
we use `yarn`

2024-07-29 18:51 UTC, pqoqubbw commented on src/components/Layout/header/header-list-icons/headerListIcons.tsx
> +    console.log(Object.keys(searchToken))
remove log

2024-07-29 18:51 UTC, pqoqubbw commented on src/components/Modal-custom-btn/ModalCustomWindow.tsx
> +    callback && callback()
```suggestion
    callback?.()
```

2024-07-29 18:53 UTC, Tkachenko01001 commented
https://app.clickup.com/t/8693kw1kr
https://app.clickup.com/t/8693kqvhx

2024-08-08 16:29 UTC, merged