Feature/feedback adaptive
sushka2023/sushka-shop-fe pull request #84
Opened 2024-07-28 17:07 UTC by sivlvy

2024-07-28 17:18 UTC, pqoqubbw requested changes

2024-07-28 17:18 UTC, pqoqubbw commented on src/components/feedbacks/Feedbacks.module.scss
> +  //}
remove unused code

2024-07-29 16:52 UTC, sivlvy commented
https://app.clickup.com/t/869563kng

2024-07-29 18:37 UTC, pqoqubbw approved these changes

2024-08-10 23:44 UTC, pqoqubbw requested changes

2024-08-10 23:44 UTC, pqoqubbw commented on src/components/feedbacks/form/FeedbackForm.tsx
> +          <input
use input from mui

2024-08-16 18:03 UTC, pqoqubbw approved these changes

2024-08-21 18:33 UTC, pqoqubbw requested changes

2024-08-21 18:33 UTC, pqoqubbw commented on src/components/Layout/header/header-nav/headerNav.tsx
> +  console.log(allCategories)
remove console.log

2024-08-21 18:33 UTC, pqoqubbw commented on src/redux/products/operation.ts
> +    console.log(response.data)
same here

2024-08-21 18:43 UTC, merged