add/data_grid
sushka2023/sushka-shop-fe pull request #87
Opened 2024-08-01 02:28 UTC by Tkachenko01001

https://app.clickup.com/t/8692wp6a7

2024-08-04 23:36 UTC, pqoqubbw requested changes

2024-08-04 23:36 UTC, pqoqubbw commented on src/pages/crm-orders-page/constants.ts
shouldn't these statuses be taken from generated types from the backend?

2024-08-04 23:36 UTC, pqoqubbw commented on src/pages/crm-orders-page/dataGridTable.tsx
> +        </Box>
why do you need `Box` here?

2024-08-04 23:36 UTC, pqoqubbw commented on src/pages/crm-orders-page/dataGridTable.tsx
> +        </Box>
same here

2024-08-06 02:27 UTC, Tkachenko01001 commented on src/pages/crm-edit-order-page/utils.ts
> +/* eslint-disable complexity */
I haven't figured out how to simplify this code yet

2024-08-06 14:47 UTC, pqoqubbw requested changes

2024-08-06 14:47 UTC, pqoqubbw commented on src/pages/crm-orders-page/constants.ts
> +  'new': {
this value should be enum not string [FROM_BACKEND.STATUS]: ...

2024-08-07 15:40 UTC, pqoqubbw approved these changes

2024-08-08 16:27 UTC, merged