Adaptation/snackbar
sushka2023/sushka-shop-fe pull request #90
Opened 2024-08-12 07:55 UTC by San88Francisco

2024-08-12 22:26 UTC, pqoqubbw requested changes

2024-08-12 22:26 UTC, pqoqubbw commented on src/components/Account-panel/Account-nav/Tabs.tsx
> +type PropsType = {
```suggestion
type Props = {
```

2024-08-12 22:26 UTC, pqoqubbw commented on src/components/Account-panel/Account-nav/Accordions.tsx
> +type PropsType = {
```suggestion
type Props = {
```

2024-08-12 22:26 UTC, pqoqubbw commented on src/components/Account-panel/Account-nav/Tabs.tsx
> +  const handleChange = (_event: SyntheticEvent, newValue: number) => {
why do you pass `_event` if you do not use it?

2024-08-12 22:26 UTC, pqoqubbw commented on src/constants/account/accordions.tsx
> +export const accordions = [
```suggestion
export const ACCORDIONS = [
```

2024-08-12 22:26 UTC, pqoqubbw commented on src/utils/accordions-panel/accordions-panel.tsx
> +type CustomAccordionProps = {
```suggestion
type Props = {
```

2024-08-12 22:26 UTC, pqoqubbw commented on src/utils/tab-panel/tab-panel.tsx
> +type TabPanelProps = {
```suggestion
type Props = {
```

2024-08-13 10:54 UTC, San88Francisco commented on src/components/Account-panel/Account-nav/Tabs.tsx
> +type PropsType = {
done

2024-08-13 10:54 UTC, San88Francisco commented on src/components/Account-panel/Account-nav/Accordions.tsx
> +type PropsType = {
done

2024-08-13 11:15 UTC, San88Francisco commented on src/components/Account-panel/Account-nav/Tabs.tsx
> +  const handleChange = (_event: SyntheticEvent, newValue: number) => {
corrected

2024-08-13 11:18 UTC, San88Francisco commented on src/utils/accordions-panel/accordions-panel.tsx
> +type CustomAccordionProps = {
done

2024-08-13 11:18 UTC, San88Francisco commented on src/constants/account/accordions.tsx
> +export const accordions = [
done

2024-08-13 11:19 UTC, San88Francisco commented on src/utils/tab-panel/tab-panel.tsx
> +type TabPanelProps = {
done

2024-08-14 00:09 UTC, pqoqubbw requested changes

2024-08-14 00:09 UTC, pqoqubbw commented on src/components/modal-portal/ModalPortal.tsx
> -
?

2024-08-14 06:55 UTC, San88Francisco commented on src/components/modal-portal/ModalPortal.tsx
> -
ops....

2024-08-14 06:55 UTC, San88Francisco commented on src/components/modal-portal/ModalPortal.tsx
> -
corected

2024-08-26 00:17 UTC, merged