fix/ search autocomplete
sushka2023/sushka-shop-fe pull request #95
Opened 2024-08-29 15:46 UTC by San88Francisco

2024-08-30 16:14 UTC, pqoqubbw requested changes

2024-08-30 16:14 UTC, pqoqubbw commented on src/components/RadioForm/BranchesNP.tsx
> +      console.log('good')
remove console.log

2024-08-30 16:14 UTC, pqoqubbw commented on src/hooks/useNovaPoshtaCity.ts
> +    console.log('No match found')
same here

2024-08-31 17:52 UTC, San88Francisco commented on src/components/RadioForm/BranchesNP.tsx
> +      console.log('good')
done

2024-08-31 17:52 UTC, San88Francisco commented on src/hooks/useNovaPoshtaCity.ts
> +    console.log('No match found')
done

2024-08-31 17:53 UTC, San88Francisco commented
ready

2024-09-11 17:35 UTC, merged